/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OpportunityOppIdRouteImport } from './routes/opportunity.$oppId'
import { Route as AdminOpportunitiesIndexRouteImport } from './routes/admin.opportunities.index'
import { Route as AdminOpportunitiesNewRouteImport } from './routes/admin.opportunities.new'
import { Route as AdminOpportunitiesOppIdEditRouteImport } from './routes/admin.opportunities.$oppId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunityOppIdRoute = OpportunityOppIdRouteImport.update({
  id: '/opportunity/$oppId',
  path: '/opportunity/$oppId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpportunitiesIndexRoute = AdminOpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesNewRoute = AdminOpportunitiesNewRouteImport.update({
  id: '/opportunities/new',
  path: '/opportunities/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOpportunitiesOppIdEditRoute =
  AdminOpportunitiesOppIdEditRouteImport.update({
    id: '/opportunities/$oppId/edit',
    path: '/opportunities/$oppId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/opportunity/$oppId': typeof OpportunityOppIdRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/opportunities/$oppId/edit': typeof AdminOpportunitiesOppIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/opportunity/$oppId': typeof OpportunityOppIdRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/opportunities': typeof AdminOpportunitiesIndexRoute
  '/admin/opportunities/$oppId/edit': typeof AdminOpportunitiesOppIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/opportunity/$oppId': typeof OpportunityOppIdRoute
  '/admin/opportunities/new': typeof AdminOpportunitiesNewRoute
  '/admin/opportunities/': typeof AdminOpportunitiesIndexRoute
  '/admin/opportunities/$oppId/edit': typeof AdminOpportunitiesOppIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/home'
    | '/login'
    | '/profile'
    | '/search'
    | '/opportunity/$oppId'
    | '/admin/opportunities/new'
    | '/admin/opportunities/'
    | '/admin/opportunities/$oppId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/home'
    | '/login'
    | '/profile'
    | '/search'
    | '/opportunity/$oppId'
    | '/admin/opportunities/new'
    | '/admin/opportunities'
    | '/admin/opportunities/$oppId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/home'
    | '/login'
    | '/profile'
    | '/search'
    | '/opportunity/$oppId'
    | '/admin/opportunities/new'
    | '/admin/opportunities/'
    | '/admin/opportunities/$oppId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  OpportunityOppIdRoute: typeof OpportunityOppIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunity/$oppId': {
      id: '/opportunity/$oppId'
      path: '/opportunity/$oppId'
      fullPath: '/opportunity/$oppId'
      preLoaderRoute: typeof OpportunityOppIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/opportunities/': {
      id: '/admin/opportunities/'
      path: '/opportunities'
      fullPath: '/admin/opportunities/'
      preLoaderRoute: typeof AdminOpportunitiesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities/new': {
      id: '/admin/opportunities/new'
      path: '/opportunities/new'
      fullPath: '/admin/opportunities/new'
      preLoaderRoute: typeof AdminOpportunitiesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opportunities/$oppId/edit': {
      id: '/admin/opportunities/$oppId/edit'
      path: '/opportunities/$oppId/edit'
      fullPath: '/admin/opportunities/$oppId/edit'
      preLoaderRoute: typeof AdminOpportunitiesOppIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOpportunitiesNewRoute: typeof AdminOpportunitiesNewRoute
  AdminOpportunitiesIndexRoute: typeof AdminOpportunitiesIndexRoute
  AdminOpportunitiesOppIdEditRoute: typeof AdminOpportunitiesOppIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOpportunitiesNewRoute: AdminOpportunitiesNewRoute,
  AdminOpportunitiesIndexRoute: AdminOpportunitiesIndexRoute,
  AdminOpportunitiesOppIdEditRoute: AdminOpportunitiesOppIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  OpportunityOppIdRoute: OpportunityOppIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
