/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrimeRouteImport } from './routes/prime'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StreaksRouteImport } from './routes/streaks'
import { Route as SchoolSchoolIdRouteImport } from './routes/school.$schoolId'
import { Route as AdminSchoolsIndexRouteImport } from './routes/admin.schools.index'
import { Route as AdminSchoolsNewRouteImport } from './routes/admin.schools.new'
import { Route as AdminSchoolsSchoolIdEditRouteImport } from './routes/admin.schools.$schoolId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimeRoute = PrimeRouteImport.update({
  id: '/prime',
  path: '/prime',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StreaksRoute = StreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolSchoolIdRoute = SchoolSchoolIdRouteImport.update({
  id: '/school/$schoolId',
  path: '/school/$schoolId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchoolsIndexRoute = AdminSchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsNewRoute = AdminSchoolsNewRouteImport.update({
  id: '/schools/new',
  path: '/schools/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsSchoolIdEditRoute =
  AdminSchoolsSchoolIdEditRouteImport.update({
    id: '/schools/$schoolId/edit',
    path: '/schools/$schoolId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/prime': typeof PrimeRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/streaks': typeof StreaksRoute
  '/school/$schoolId': typeof SchoolSchoolIdRoute
  '/admin/schools/new': typeof AdminSchoolsNewRoute
  '/admin/schools/': typeof AdminSchoolsIndexRoute
  '/admin/schools/$schoolId/edit': typeof AdminSchoolsSchoolIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/prime': typeof PrimeRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/streaks': typeof StreaksRoute
  '/school/$schoolId': typeof SchoolSchoolIdRoute
  '/admin/schools/new': typeof AdminSchoolsNewRoute
  '/admin/schools': typeof AdminSchoolsIndexRoute
  '/admin/schools/$schoolId/edit': typeof AdminSchoolsSchoolIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/prime': typeof PrimeRoute
  '/profile': typeof ProfileRoute
  '/search': typeof SearchRoute
  '/streaks': typeof StreaksRoute
  '/school/$schoolId': typeof SchoolSchoolIdRoute
  '/admin/schools/new': typeof AdminSchoolsNewRoute
  '/admin/schools/': typeof AdminSchoolsIndexRoute
  '/admin/schools/$schoolId/edit': typeof AdminSchoolsSchoolIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/home'
    | '/login'
    | '/prime'
    | '/profile'
    | '/search'
    | '/streaks'
    | '/school/$schoolId'
    | '/admin/schools/new'
    | '/admin/schools/'
    | '/admin/schools/$schoolId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/home'
    | '/login'
    | '/prime'
    | '/profile'
    | '/search'
    | '/streaks'
    | '/school/$schoolId'
    | '/admin/schools/new'
    | '/admin/schools'
    | '/admin/schools/$schoolId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/home'
    | '/login'
    | '/prime'
    | '/profile'
    | '/search'
    | '/streaks'
    | '/school/$schoolId'
    | '/admin/schools/new'
    | '/admin/schools/'
    | '/admin/schools/$schoolId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PrimeRoute: typeof PrimeRoute
  ProfileRoute: typeof ProfileRoute
  SearchRoute: typeof SearchRoute
  StreaksRoute: typeof StreaksRoute
  SchoolSchoolIdRoute: typeof SchoolSchoolIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prime': {
      id: '/prime'
      path: '/prime'
      fullPath: '/prime'
      preLoaderRoute: typeof PrimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streaks': {
      id: '/streaks'
      path: '/streaks'
      fullPath: '/streaks'
      preLoaderRoute: typeof StreaksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/$schoolId': {
      id: '/school/$schoolId'
      path: '/school/$schoolId'
      fullPath: '/school/$schoolId'
      preLoaderRoute: typeof SchoolSchoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schools/': {
      id: '/admin/schools/'
      path: '/schools'
      fullPath: '/admin/schools/'
      preLoaderRoute: typeof AdminSchoolsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools/new': {
      id: '/admin/schools/new'
      path: '/schools/new'
      fullPath: '/admin/schools/new'
      preLoaderRoute: typeof AdminSchoolsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools/$schoolId/edit': {
      id: '/admin/schools/$schoolId/edit'
      path: '/schools/$schoolId/edit'
      fullPath: '/admin/schools/$schoolId/edit'
      preLoaderRoute: typeof AdminSchoolsSchoolIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSchoolsNewRoute: typeof AdminSchoolsNewRoute
  AdminSchoolsIndexRoute: typeof AdminSchoolsIndexRoute
  AdminSchoolsSchoolIdEditRoute: typeof AdminSchoolsSchoolIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSchoolsNewRoute: AdminSchoolsNewRoute,
  AdminSchoolsIndexRoute: AdminSchoolsIndexRoute,
  AdminSchoolsSchoolIdEditRoute: AdminSchoolsSchoolIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PrimeRoute: PrimeRoute,
  ProfileRoute: ProfileRoute,
  SearchRoute: SearchRoute,
  StreaksRoute: StreaksRoute,
  SchoolSchoolIdRoute: SchoolSchoolIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
